workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_COMMIT_BRANCH'

default:
  tags: ["${CI_RUNNER_TAG}"]

variables:
  CI_RUNNER_TAG: "k8s-cluster-1"
  CI_ENVIRONMENT: "k8s-cluster-1"

.environment:
  environment: "${CI_ENVIRONMENT}"

include: staging.yml