default:
  tags: ["kubernetes"]

workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_COMMIT_BRANCH'
      when: manual
      allow_failure: true
# remove after 
.environment:
  environment: testing

include: staging.yml
