workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_COMMIT_BRANCH'

variables:
  TAG:
    value: k8s-cluster-2
    description: k8s-cluster-2 tags

  ENV_NAME:
    value: k8s-cluster-2
    description: cluster environment, k8s-cluster-2

default:
  tags: [$TAG]

.environment:
  environment: $ENV_NAME

include: staging.yml