workflow:
  rules:
    - if: $CI_COMMIT_TAG
    - if: '$CI_COMMIT_BRANCH'

variables:
  TAG: k8s-cluster-1
  ENV_NAME: k8s-cluster-1

default:
  tags: [$TAG]

.environment:
  environment: $ENV_NAME

include: staging.yml