stages:
  - prepare
  - deploy
  - deploy-charts
  - verify
  - cleanup

include:
  - services/alluxio.yml
  - services/batch-job.yml
  - services/frontend.yml
  - services/history.yml
  - services/metadata.yml
  - services/mysql.yml
  - services/spark-operator.yml
  - services/schema.yml
  - services/zeppelin.yml
  - services/rbac.yml

variables:
  CHARTS_DIR: charts
  OVERRIDES_FILE: overrides.yml
  SERVICE_NAMESPACE: "${CI_PROJECT_NAME}-${CI_PROJECT_ID}-${CI_ENVIRONMENT}"

.generator:
  # extenders need to generate a file "deployment/${PROJECT}.yml"
  stage: prepare
  image: ${CI_REGISTRY}/planetrover/infrastructure/alpine:3.15
  rules:
    - if: '($DEPLOY_PROJECT == "${PROJECT}" || $DEPLOY_PROJECT == "all") && $ONLY_CLEANUP == "false"'
  variables: {}
    # PROJECT
  artifacts:
    paths:
      - ${DEPLOYMENTS_DIR}/${PROJECT}.yml

.helm-prepare:
  stage: prepare
  extends:
    - .package-pull
  variables: {}
    # SERVICE_NAME:
    # PACKAGE_NAME:
    # FILE_NAME:
    # PACKAGE_VERSION:
    # ID:
  before_script:
    - mkdir -p ${CHARTS_DIR}/${SERVICE_NAME}/
    - cd ${CHARTS_DIR}/${SERVICE_NAME}/
  artifacts:
    paths:
      - ${CHARTS_DIR}

.verify-running:
  stage: verify
  extends:
    - .environment
  rules:
    - if: '$UPSTREAM_PROJECT == "metadata"'
  variables:
    TIMEOUT: "60"
    # SERVICE_NAME:
    # SERVICE_LABEL:
    # PROJECT:"
  script:
    - |
      while [ $(kubectl get pod -n ${SERVICE_NAMESPACE} -l ${SERVICE_LABEL} -o jsonpath="{.items[0].status.phase}") != 'Running' ]; do
       if [[ ${TIMEOUT} -le 0 ]]
        then
          echo "Timed out waiting; pod status $(kubectl get pod -n ${SERVICE_NAMESPACE} -l ${SERVICE_LABEL} -o jsonpath="{.items[0].status.phase}") != 'Running'"
          exit 1
        fi
       TIMEOUT=$((TIMEOUT-1))
       sleep 1
      done
    - kubectl describe pods -n ${SERVICE_NAMESPACE} -l ${SERVICE_LABEL}
    - echo -e "\n LOGS -------- \n"
    - kubectl logs $(kubectl get pod -n ${SERVICE_NAMESPACE} -l ${SERVICE_LABEL} -o jsonpath="{.items[0].metadata.name}") --all-containers=true


.verify-cleanup:
  stage: cleanup
  rules:
    - if: '$UPSTREAM_PROJECT == "metadata"'
      when: manual
      allow_failure: true
  extends:
    - .environment
  variables:
    TIMEOUT: "60"
    # SERVICE_NAME:
    # SERVICE_LABEL:
    # PROJECT:"
  script:
    - helm uninstall ${SERVICE_NAME} -n ${SERVICE_NAMESPACE} || true
    - kubectl delete service/${MYSQL_SERVICE_NAME} deployment/${MYSQL_SERVICE_NAME} -n ${SERVICE_NAMESPACE} || true

Deploy resources:
  # Deploy all generated resource configs in the deployments directory
  # Also install helm charts by explicitly referencing sub-scripts
  stage: deploy
  rules:
    - if: '$ONLY_CLEANUP == "false"'
  extends:
    - .environment
  script:
    - |
      if ! kubectl get sa spark -n ${SERVICE_NAMESPACE}
      then
        echo "Creating 'spark' service account"
        kubectl apply -n ${SERVICE_NAMESPACE} -f - <<EOF
        apiVersion: v1
        kind: ServiceAccount
        metadata:
          name: spark
          namespace: ${SERVICE_NAMESPACE}
      EOF
      fi

      # create mysql secret
      decoded_username=`echo "root" | base64`
      decoded_password=`echo ${MYSQL_ROOT_PASSWORD} | base64`
      kubectl apply -n ${SERVICE_NAMESPACE} -f - <<EOF
      apiVersion: v1
      kind: Secret
      metadata:
        name: ${SERVICE_NAMESPACE}-mysql-secret
        namespace: ${SERVICE_NAMESPACE}
      type: Opaque
      data:
        user: "${decoded_username}"
        password: "${decoded_password}"
      EOF

      # create s3 secrets
      decoded_access_key=`echo ${S3A_ACCESS_KEY} | base64`
      decoded_secret_key=`echo ${S3A_SECRET_KEY} | base64`
      kubectl apply -n ${SERVICE_NAMESPACE} -f - <<EOF
      apiVersion: v1
      kind: Secret
      metadata:
        name: ${SERVICE_NAMESPACE}-s3-secret
        namespace: ${SERVICE_NAMESPACE}
      type: Opaque
      data:
        accessKey: ${decoded_access_key}
        secretKey: ${decoded_secret_key}
      EOF

      if [ -d "${DEPLOYMENTS_DIR}/" ] 
      then
        echo "Deploying the following files"
        ls ${DEPLOYMENTS_DIR}/
        kubectl apply -n ${SERVICE_NAMESPACE} -f ${DEPLOYMENTS_DIR}/
      else
        echo "No resources to deploy"
      fi

Deploy helm charts:
  # Install all helm charts
  stage: deploy-charts
  rules:
    - if: '$ONLY_CLEANUP == "false"'
  extends:
    - .environment
  script:
    - |
      ls -lRt ${CHARTS_DIR}/
      if [ -d "${CHARTS_DIR}/" ]
      then
        for SERVICE in $(ls ${CHARTS_DIR}) ; do
          [[ ${ENABLE_ALLUXIO} -eq 0 ]] && [[ ${SERVICE} == "alluxio" ]] && continue

          echo "Installing/upgrading service ${SERVICE}..."
          HELM_COMMAND="helm upgrade --install -n ${SERVICE_NAMESPACE} --values ${CHARTS_DIR}/${SERVICE}/${OVERRIDES_FILE} ${SERVICE} ${CHARTS_DIR}/${SERVICE}/*.tgz"
          echo "${HELM_COMMAND}"
          ${HELM_COMMAND}
        done
      else
        echo "No helm charts to deploy"
      fi

Cleanup services:
  # Remove all services
  stage: cleanup
  rules:
    - if: '$ONLY_CLEANUP == "true"'
  extends:
    - .environment
  dependencies: [] # skip downloading any artifacts
  variables:
    TIMEOUT: "60"
  script:
    - echo "kubectl exec ${ALLUXIO_SVC} -n ${SERVICE_NAMESPACE} -c alluxio-master -- alluxio fs rm -RU /${SPARK_WAREHOUSE}"
    - kubectl exec ${ALLUXIO_SVC} -n ${SERVICE_NAMESPACE} -c alluxio-master -- alluxio fs rm -RU /${SPARK_WAREHOUSE} || true
    - echo "kubectl exec ${ALLUXIO_SVC} -n ${SERVICE_NAMESPACE} -c alluxio-master -- alluxio fs rm -RU /${SPARK_DEPENDENCY_DIR}"
    - kubectl exec ${ALLUXIO_SVC} -n ${SERVICE_NAMESPACE} -c alluxio-master -- alluxio fs rm -RU /${SPARK_DEPENDENCY_DIR} || true
    - echo "helm uninstall -n ${SERVICE_NAMESPACE} ${ALLUXIO_SERVICE_NAME} alluxio-charts/alluxio"
    - helm uninstall -n ${SERVICE_NAMESPACE} ${ALLUXIO_SERVICE_NAME} alluxio-charts/alluxio || true
    - echo "kubectl delete pod ${SPARK_DRIVER_POD_NAME} -n ${SERVICE_NAMESPACE} --ignore-not-found=true"
    - kubectl delete pod ${SPARK_DRIVER_POD_NAME} -n ${SERVICE_NAMESPACE} --ignore-not-found=true || true
    - echo "kubectl delete service/${MYSQL_SERVICE_NAME} deployment/${MYSQL_SERVICE_NAME} -n ${SERVICE_NAMESPACE}"
    - kubectl delete service/${MYSQL_SERVICE_NAME} deployment/${MYSQL_SERVICE_NAME} -n ${SERVICE_NAMESPACE} || true
    - |
      for SERVICE in ${ZEPPELIN_SERVICE_NAME} ${SCHEMA_SERVICE_NAME} ${METADATA_SERVICE_NAME} ${HISTORY_SERVICE_NAME} \
        ${FRONTEND_SERVICE_NAME} ${BATCH_JOB_SERVICE_NAME} ${SPARK_OPERATOR_SERVICE_NAME} ${RBAC_SERVICE_NAME}
      do
        echo "helm uninstall ${SERVICE} -n ${SERVICE_NAMESPACE}"
        helm uninstall ${ZEPPELIN_SERVICE_NAME} -n ${SERVICE_NAMESPACE} || true
      done
    - echo "kubectl delete sa ${SPARK_OPERATOR_SERVICE_NAME} -n ${SERVICE_NAMESPACE}"
    - kubectl delete sa ${SPARK_OPERATOR_SERVICE_NAME} -n ${SERVICE_NAMESPACE} || true
    - echo "Waiting for resources to cleanup..."
    - |
      while [[ $(kubectl get pods -n ${SERVICE_NAMESPACE} --no-headers | wc -l) -gt 0 ]] &&
            [[ $(kubectl get services -n ${SERVICE_NAMESPACE} --no-headers | wc -l) -gt 0 ]]
      do
        if [[ ${TIMEOUT} -le 0 ]]
        then
          echo "Timed out waiting for resources to cleanup"
          exit 1
        fi
        TIMEOUT=$((TIMEOUT-1))
        sleep 1
      done
      kubectl delete secret ${PULL_SECRET} -n ${SERVICE_NAMESPACE} --ignore-not-found=true