variables:
  SCHEMA_SERVICE_NAME: schema
  SCHEMA_SVC: ${SCHEMA_SERVICE_NAME}:9083
  SCHEMA_PROJECT_ID: 50

Schema helm prepare:
  extends:
    - .helm-prepare
  rules:
    - if: '($DEPLOY_PROJECT =~ /schema/ || $DEPLOY_PROJECT == "all") && $ONLY_CLEANUP == "false"'
  variables:
    SERVICE_NAME: ${SCHEMA_SERVICE_NAME}
    PACKAGE_NAME: helm-chart
    FILE_NAME: hive-metastore-0.1.0.tgz
    PACKAGE_VERSION: "0.1.0"
    ID: ${SCHEMA_PROJECT_ID}
  script:
    - !reference [".helm-prepare", "script"]
    - |
      cat << EOF > ${OVERRIDES_FILE}
      image:
        registry: ${REGISTRY}
        repository: sequoiadp/hive
        tag: ${SCHEMA_IMAGE_TAG}
        pullSecrets: 
          - name: ${PULL_SECRET}
        pullPolicy: Always
      fullnameOverride: ${SCHEMA_SERVICE_NAME}
      mysql:
        mysqlHost: ${MYSQL_SERVICE_NAME}
        mysqlDatabase: metastore
        mysqlUser: root
        mysqlPassword: ${MYSQL_ROOT_PASSWORD}
        initdbScriptsConfigMap: hive-metastore-mysql-init
      s3:
        accessKey: ${S3A_ACCESS_KEY}
        secretAccessKey: ${S3A_SECRET_KEY}
        endpoint: ${S3A_ENDPOINT}
        sslEnabled: false
      EOF
      cat ${OVERRIDES_FILE}